### ISSUE TITLE
为何不把view抽出来，DepthMapOrderLeftView这个基本没法用，只能自己拆了封装

### ISSUE THREAD

**Issue by hloong** [ciscolxh/DepthMapView#1]
你这很多View都是一次性写死了，最好是抽出来，DepthMapOrderLeftView这个里面竟然数量和价格共用的一个textPaint，哎，看样子又得自己花时间弄了

**Comment by ciscolxh** [comment]
主要是提供一个思路具体还是得自己封装了。希望对你有帮助
